# Generated by Django 2.0.2 on 2018-04-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corredor',
            name='bicicleta',
        ),
        migrations.AddField(
            model_name='corredor',
            name='bicicleta',
            field=models.ManyToManyField(blank=True, null=True, to='bike.Bicicleta'),
        ),
    ]
